name: On Plugin Release Create Tag

on:
  repository_dispatch:
    types: onPluginReleaseCreateTag

jobs:
  build:
    name: Create tag for private plugin release
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{github.event.client_payload.tag}}
          tag_exists_error: false
          message: "Latest release"
